# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: 
  name: docker:stable
  username: paperapp
  password: $DOCKER_PW
  email: accounts@get-paper.com

options:
  docker: true

pipelines:
  default:
    - step:
      - echo "Tmp"
  
  branches:
    pqa-july-2018:
      - step:
          caches:
            - node
            - pip
            - docker
          script: 
            - apk add --no-cache py-pip bash 
            - pip install --no-cache-dir docker-compose
            - docker-compose -v
            - docker-compose run runner conf.js
            